### ISSUE TITLE
could not get it to work

### ISSUE THREAD

**Issue by Firas95k** [3DCoded/DynamicMacros#3] opened 2024-08-06 23:20 UTC
I followed the instructions but never was able to run them, attached my klippy.log and configs 
Thank you very much for your efforts, I am following your contributions here and on 3d Chameleon and Klipper Discourse.
[klippy.log](https://github.com/user-attachments/files/16516529/klippy.log)
[config-20240807-021449.zip](https://github.com/user-attachments/files/16516530/config-20240807-021449.zip)

**Comment by 3DCoded** [comment] 2024-08-07 10:29
I don't see anything immediately wrong from looking at your logs and config. Thank you for uploading them from the start! Can you please explain what you couldn't get to work? If you can't run the macro directly, does the `DYNAMIC_MACRO` command work? If not, try restarting Klipper **from the terminal** with `sudo service klipper restart`.

**Comment by 3DCoded** [comment] 2024-08-07 18:54
The `ERROR` message means the macro wasn't found. I didn't see `TOOL_INIT` in your `dynamic_macros.cfg`. Are you able to run this? (should output "Hello world!" to your printer's screen)
```
DYNAMIC_MACRO MACRO=MYTEST
```
or this? (should heat hotend to 200)
```
DYNAMIC_MACRO MACRO=HEAT_HOTEND TEMP=200
```

**Comment by 3DCoded** [comment] 2024-08-07 19:02
I would also recommend updating your Klipper if it isn't already on the latest version.

**Comment by Firas95k** [comment] 2024-08-07 19:22
Here are my update config files and klippy.log, same Error appears.

![image](https://github.com/user-attachments/assets/c2b739fb-1e92-4d40-958f-c48d9fe42385)
[klippy.zip](https://github.com/user-attachments/files/16533160/klippy.zip)
[config-20240807-221807.zip](https://github.com/user-attachments/files/16533164/config-20240807-221807.zip)

**Comment by Firas95k** [comment] 2024-08-07 19:26
Also I am using the latest updates 
![image](https://github.com/user-attachments/assets/a48494e2-bbe2-4f19-8aef-823f5fccec3f)

**Comment by Firas95k** [comment] 2024-08-07 20:28
Thank you for the quick follow ups, done
[klippy.zip](https://github.com/user-attachments/files/16533905/klippy.zip)

**Comment by 3DCoded** [comment] 2024-08-07 20:53
Thank you for the new logs. Based on this, the issue is in parsing the `.cfg` file. What is the path to your configuration folder from the home folder (`~`)? DynamicMacros assumes it is `~/printer_data/config/`. I added a check to the `logging` branch that will raise an error if the configuration file is not found. Update it using:

```
cd ~/DynamicMacros
git pull
sh install.sh
sudo service klipper restart
```

If Klipper reports an error about a missing file, that means the configuration file isn't where DynamicMacros expected it to be. If that's the case, let me know and I can make that a configurable option.

**Comment by Firas95k** [comment] 2024-08-07 21:08
right I am not using the default location, I have 3 instances of Klipper installed on my RPI 4, one for each of my 2 printers (Voron and E3 V2) and the third for various experiments with other boards. It would be awesome if you can make the printer config path configurable.

![image](https://github.com/user-attachments/assets/478c8e67-c290-47ac-a063-8f49f60c3003)

**Comment by Firas95k** [comment] 2024-08-07 21:24
Everything works like charm, thank you for kind help 💐💐, I ran all my Dynamic Gcodes

**Comment by 3DCoded** [comment] 2024-08-07 21:30
Thank you for your patience in helping me resolve this issue. I've merged this into the `main` branch. To switch back to the `main` branch:
```
cd ~/DynamicMacros
git checkout main
git pull
sh install.sh
sudo service klipper restart
```

**Closed by 3DCoded** 2024-08-07 21:30 UTC
Labels: bug, configuration
