### ISSUE TITLE
[Bug]: Error on M104 S: unable to parse when enabling dynamic macros

### ISSUE THREAD

**Issue by plandevida** [3DCoded/DynamicMacros#10] opened 2024-11-05 13:42 UTC
### What happened?

I tried to print right after enabling dynamic macros and I encounter this error and the print is cancelled.

<img width="697" alt="SCR-20241105-nafr" src="https://github.com/user-attachments/assets/ac15da65-ef6c-4da3-9523-451633bdaef6">

Right after the error I disabled dynamic macros and hit print for the same file, and it just started as expected, see:

<img width="814" alt="SCR-20241105-nait" src="https://github.com/user-attachments/assets/7a5a032f-e376-4a13-9a1a-fcea0f1e6178">

### Klippy Log

[klippy.log](https://github.com/user-attachments/files/17633367/klippy.log)

**Comment by 3DCoded** [comment] 2024-11-05 13:54
Does running `M104 S200` heat the hotend to 200 degrees? Does runing `M104 S0` cool the hotend?

The `unable to parse` message is a Klipper error. Running `M104 S` is an incomplete G-Code command.

I would recommend checking your slicer start G-Code and your `PRINT_START` to make sure the temperature variables are being correctly evaluated. You can use [rendering](https://3dcoded.github.io/DynamicMacros/features/rendering/) to help.

**Comment by 3DCoded** [comment] 2024-11-05 14:36
I think I found the bug, and it may have to do with DynamicMacros's method of splitting macros for [variable updates](https://3dcoded.github.io/DynamicMacros/features/receivingvariables/). Can you please upload your macros file so I can test on my end?

**Comment by 3DCoded** [comment] 2024-11-07 17:09
Can you try removing all empty lines spaces in your `PRINT_START` macro? Also, please upload your macros file.

**Comment by plandevida** [comment] 2024-11-23 12:52
Hey! I tried removing al the empty lines form the `PRINT_START` macro and I got the same error:

`13:50
Error on 'M104 S': unable to parse
13:50
Error on 'M104 S': unable to parse
13:50
Error on 'M104 S': unable to parse
13:50
Error on 'M140 S': unable to parse
13:50
Error on 'M140 S': unable to parse
13:50
Mesh Bed Leveling Complete
13:50
probe at 131.000,105.000 is z=1.736250
13:50
probe at 131.000,105.000 is z=1.743750
13:50
probe at 131.000,105.000 is z=1.755000
13:50
probe at 119.000,105.000 is z=1.736250
13:50
probe at 119.000,105.000 is z=1.742500
13:50
probe at 119.000,105.000 is z=1.751250
13:50
probe at 107.000,105.000 is z=1.717500
13:50
probe at 107.000,105.000 is z=1.721250
13:50
probe at 107.000,105.000 is z=1.733750
13:50
probe at 107.000,93.000 is z=1.731250
13:50
probe at 107.000,93.000 is z=1.736250
13:50
probe at 107.000,93.000 is z=1.751250
13:50
probe at 119.000,93.000 is z=1.757500
13:50
probe at 119.000,93.000 is z=1.770000
13:50
probe at 119.000,93.000 is z=1.773750
13:50
probe at 131.000,93.000 is z=1.731250
13:50
probe at 131.000,93.000 is z=1.735000
13:50
probe at 131.000,93.000 is z=1.746250
13:50
probe at 131.000,81.000 is z=1.708750
13:50
probe at 131.000,81.000 is z=1.711250
13:50
probe at 131.000,81.000 is z=1.722500
13:50
probe at 119.000,81.000 is z=1.716250
13:50
probe at 119.000,81.000 is z=1.723750
13:50
probe at 119.000,81.000 is z=1.731250
13:49
probe at 107.000,81.000 is z=1.730000
13:49
probe at 107.000,81.000 is z=1.735000
13:49
probe at 107.000,81.000 is z=1.745000
13:49
8   | (131.0, 105.0)  | (102.0, 102.0)
13:49
7   | (119.0, 105.0)  | (90.0, 102.0)
13:49
6   | (107.0, 105.0)  | (78.0, 102.0)
13:49
5   | (107.0, 93.0)   | (78.0, 90.0)
13:49
4   | (119.0, 93.0)   | (90.0, 90.0)
13:49
3   | (131.0, 93.0)   | (102.0, 90.0)
13:49
2   | (131.0, 81.0)   | (102.0, 78.0)
13:49
1   | (119.0, 81.0)   | (90.0, 78.0)
13:49
0   | (107.0, 81.0)   | (78.0, 78.0)
13:49
bed_mesh: generated points
Index |  Tool Adjusted  |   Probe
13:49
Generating new points...
13:49
Adapted probe count: (3,3)
13:49
Ratio: (0.183206106870229, 0.15286624203821655)
13:49
Adapted mesh bounds: ([78.0, 78.0],[102.0, 102.0])
13:49
Original probe count: (4,4)
13:49
Original mesh bounds: ((10.0, 10.0),(141.0, 167.0))
13:49
Found 1 objects
13:48
LOAD_PLA
13:47
File selected
13:47
File opened:Cylinder_0.2mm_PLA_MINI.gcode Size:189491
13:47
SDCARD_PRINT_FILE FILENAME="Cylinder_0.2mm_PLA_MINI.gcode"`

**Comment by plandevida** [comment] 2024-11-23 12:54
Are you publishing the branch with the fix? I could try it too

**Comment by 3DCoded** [comment] 2024-11-23 14:14
I haven't found the root cause of the issue yet. Could you please share the output of using [rendering](https://3dcoded.github.io/DynamicMacros/features/rendering/) on your macro?

**Comment by 3DCoded** [comment] 2024-11-24 04:34
Those extra comments may be causing an issue. I may have a fix almost figured out. Could you try removing all comments and blank lines in your macro and let me know if that works? If it works, I will know the root cause of the issue and can implement a fix.

**Comment by plandevida** [comment] 2024-11-24 13:27
Okay I just did remove all the comments and empty lines and I got to run a print with no errors until it ran another macro I didn't modified.

```
14:24
Error evaluating 'PARK_TOOLHEAD': jinja2.exceptions.UndefinedError: 'MAX_LAYER_Z' is undefined
14:24
Error evaluating 'PARK_TOOLHEAD': jinja2.exceptions.UndefinedError: 'MAX_LAYER_Z' is undefined
14:24
[END_PRINT] Saving GCODE state
14:24
[END_PRINT] Set relative coordinates
14:12
pressure_advance: 0.080000
pressure_advance_smooth_time: 0.040000
14:12
KAMP purge starting at 82.5, 71.0 and purging 15.0mm of filament, requested flow rate is 12.0mm3/s.
14:12
KAMP purge is not using firmware retraction, it is recommended to configure it.
14:12
Moving filament tip 2.0mms
14:11
Smart Park location: 71.0,71.0.
14:11
Mesh Bed Leveling Complete
14:11
probe at 131.000,105.000 is z=1.750000
14:11
probe at 131.000,105.000 is z=1.756250
14:11
probe at 131.000,105.000 is z=1.767500
14:11
probe at 119.000,105.000 is z=1.766250
14:10
probe at 119.000,105.000 is z=1.771250
14:10
probe at 119.000,105.000 is z=1.781250
14:10
probe at 107.000,105.000 is z=1.735000
14:10
probe at 107.000,105.000 is z=1.740000
14:10
probe at 107.000,105.000 is z=1.750000
14:10
probe at 107.000,93.000 is z=1.747500
14:10
probe at 107.000,93.000 is z=1.752500
14:10
probe at 107.000,93.000 is z=1.760000
14:10
probe at 119.000,93.000 is z=1.780000
14:10
probe at 119.000,93.000 is z=1.786250
14:10
probe at 119.000,93.000 is z=1.795000
14:10
probe at 131.000,93.000 is z=1.760000
14:10
probe at 131.000,93.000 is z=1.765000
14:10
probe at 131.000,93.000 is z=1.772500
14:10
probe at 131.000,81.000 is z=1.737500
14:10
probe at 131.000,81.000 is z=1.742500
14:10
probe at 131.000,81.000 is z=1.751250
14:10
probe at 119.000,81.000 is z=1.725000
14:10
probe at 119.000,81.000 is z=1.730000
14:10
probe at 119.000,81.000 is z=1.740000
14:10
probe at 107.000,81.000 is z=1.741250
14:10
probe at 107.000,81.000 is z=1.745000
14:10
probe at 107.000,81.000 is z=1.756250
14:10
8   | (131.0, 105.0)  | (102.0, 102.0)
14:10
7   | (119.0, 105.0)  | (90.0, 102.0)
14:10
6   | (107.0, 105.0)  | (78.0, 102.0)
14:10
5   | (107.0, 93.0)   | (78.0, 90.0)
14:10
4   | (119.0, 93.0)   | (90.0, 90.0)
14:10
3   | (131.0, 93.0)   | (102.0, 90.0)
14:10
2   | (131.0, 81.0)   | (102.0, 78.0)
14:10
1   | (119.0, 81.0)   | (90.0, 78.0)
14:10
0   | (107.0, 81.0)   | (78.0, 78.0)
14:10
bed_mesh: generated points
Index |  Tool Adjusted  |   Probe
14:10
Generating new points...
14:10
Adapted probe count: (3,3)
14:10
Ratio: (0.183206106870229, 0.15286624203821655)
14:10
Adapted mesh bounds: ([78.0, 78.0],[102.0, 102.0])
14:10
Original probe count: (4,4)
14:10
Original mesh bounds: ((10.0, 10.0),(141.0, 167.0))
14:10
Found 1 objects
14:08
File selected
14:08
File opened:Cylinder_0.2mm_PLA_MINI.gcode Size:189491
```

<img width="831" alt="SCR-20241124-mvvn" src="https://github.com/user-attachments/assets/642ae93a-e62e-4a16-a2cf-2e3b9584a5d8">

**Comment by 3DCoded** [comment] 2024-11-24 19:55
Since the `PRINT_START` macro worked when removing comments, I was able to implement an experimental fix. Could you please switch to the `dev` branch, update, and let me know how it works?
```
cd ~/DynamicMacros
git checkout dev
git pull
sh install.sh
```
You will need to add the following option to your `[dynamicmacros]` config section:
```
delimeter: NO_DELIMETER
```

**Comment by plandevida** [comment] 2024-11-24 23:50
Hi!

I tried and it seems that the new configuration option is not accepted:

<img width="419" alt="SCR-20241125-brfv" src="https://github.com/user-attachments/assets/0ed62f94-43b1-441f-9b09-37c12e943b0c">
<img width="632" alt="SCR-20241125-brnv" src="https://github.com/user-attachments/assets/810312aa-5422-4ff6-a193-1708928589ed">
<img width="1197" alt="image" src="https://github.com/user-attachments/assets/2947a560-4b21-425f-8007-dc02951c522e">

**Comment by 3DCoded** [comment] 2024-11-25 11:32
Did you restart the Klipper **service**, or just via the `RESTART` command? Try this in SSH:
```
sudo service klipper restart
```

**Comment by plandevida** [comment] 2024-11-25 12:53
I tried both, same issue.

**Comment by 3DCoded** [comment] 2024-11-25 12:57
Hmm...Could you manually install it with:
```
cd ~/DynamicMacros
cp dynamicmacros.py ~/klipper/klippy/extras/dynamicmacros.py
sudo service klipper restart
```

I'm a bit concerned that `git pull` reported `Already up to date`. If the above commands don't work, try these to reinstall DynamicMacros to the `dev` branch:

```
cd ~/
rm -rf DynamicMacros
git clone https://github.com/3DCoded/DynamicMacros
cd DynamicMacros
git checkout dev
sh install.sh
sudo service klipper restart
```

**Comment by plandevida** [comment] 2024-11-25 13:01
That's I already pulled the branch.

I did execute your last commands right now:

<img width="568" alt="SCR-20241125-mmbx" src="https://github.com/user-attachments/assets/61c65508-c92f-44d2-9e28-386e529cafa4">

<img width="685" alt="SCR-20241125-mmev" src="https://github.com/user-attachments/assets/1b08d46b-7515-4f62-92c0-ed1da9a24c26">

**Comment by 3DCoded** [comment] 2024-11-25 13:31
I found the issue. I put the option in the macro itself, not `dynamicmacros`. I've pushed a fix for this. Could you update and try again?
Sorry for the errors.

**Comment by plandevida** [comment] 2024-11-26 00:00
I have a 8h printing ongoing ;), tomorrow it give it a try

**Comment by plandevida** [comment] 2024-11-26 11:41
okay Its working for me!

I believe this is a temporary fix, I think the delimeter parameter is not very user friendly or meaningful.

Thanks for the effort fixing this.

I think I found another issue when loading the configuration un subfolders, I will create another ticket.

**Comment by plandevida** [comment] 2024-11-26 11:45
I just tested again the same scenario that was giving me errors loading nested configurations, it seems to work just fine

**Comment by 3DCoded** [comment] 2024-11-26 11:47
I'm glad its mostly working now!

> I believe this is a temporary fix, I think the delimeter parameter is not very user friendly or meaningful.

I'm working on documentation for the `delimeter` parameter. Its uses wouldn't just be for solving issues like this. It would be best used to allow more complex macro syntax while still working with [Receiving Variable Updates](https://3dcoded.github.io/DynamicMacros/features/receivingvariables/). I still need to do more testing on my end, but you _should_ be able to set `delimeter` to anything (e.g. `-----`) and use that to split macros instead of the extra spaces (which ignores comments).

> I just tested again the same scenario that was giving me errors loading nested configurations, it seems to work just fine

If the issue happens again, let me know.

**Comment by 3DCoded** [comment] 2024-11-26 17:42
Closing this issue as it is now in the main branch. To switch back to the `main` branch:

```
cd ~/DynamicMacros
git checkout main
git pull
sh install.sh
sudo service klipper restart
```

**Closed by 3DCoded** 2024-11-26 17:42 UTC
Labels: bug
